name: Defect Prediction Pipeline

on:
  push:
    branches:
      - main

jobs:
  test-pipeline:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test Pipeline
        run: echo "GitHub Actions triggered successfully!"

      - name: Send repository information to backend
        run: |
          curl -X POST "https://renewed-share-tartar.ngrok-free.dev/analyze" \
          -H "Content-Type: application/json" \
          -d '{
            "repository": "${{ github.event.repository.name }}",
            "commitId": "${{ github.sha }}"
          }'
